"""
build_dashboard_from_cwts.py
============================
Generates the scope drift dashboard from either local CWTS files or BigQuery.
Uses render_script.js for visualization.

Data source (toggle via DATA_SOURCE env var):
    - "local" (default): reads from cwts_output/*.txt files
    - "bigquery": reads from BigQuery tables using RUN_TIMESTAMP

Input files (when DATA_SOURCE=local):
    - cwts_output/classification.txt
    - cwts_output/pub_metadata.txt
    - cwts_output/cit_links.txt

BigQuery tables (when DATA_SOURCE=bigquery):
    - classification_raw_{RUN_TIMESTAMP}
    - pub_metadata_raw_{RUN_TIMESTAMP}
    - cit_links_raw_{RUN_TIMESTAMP}

Output:
    - output/scope_dashboard.html

Environment variables:
    - DATA_SOURCE: "local" or "bigquery" (default: local)
    - RUN_TIMESTAMP: required when DATA_SOURCE=bigquery
    - CLUSTER_LEVEL: micro, meso, or macro (default: macro)
"""

import json
import logging
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd
import os

# ──────────────────────────────────────────────────────────────────────────────
# CONFIG
# ──────────────────────────────────────────────────────────────────────────────
CWTS_DIR = Path(__file__).resolve().parent.parent / "cwts_output"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "output" / "scope_dashboard.html"
RENDER_SCRIPT_PATH = Path(__file__).resolve().parent.parent / "render_script.js"

# Data source toggle: "local" (CWTS files) or "bigquery"
# Can be overridden via DATA_SOURCE env var
DATA_SOURCE = os.environ.get("DATA_SOURCE", "local").lower()  # Options: local, bigquery

# Which cluster level to use as "communities"
# Can be overridden via CLUSTER_LEVEL env var
CLUSTER_LEVEL = os.environ.get("CLUSTER_LEVEL", "macro")  # Options: micro, meso, macro

# Primary clusters = smallest set covering this % of papers
PRIMARY_COVERAGE = 0.8

# GPT labels file (generated by label_clusters.py)
# Format: short_label, long_label, ..., level, cluster_id, n_papers
GPT_LABELS_PATH = Path(__file__).resolve().parent.parent / "cwts_output"

# Target journals (filter to these)
JOURNALS = [
    "Frontiers in Immunology",
    "Frontiers in Public Health",
    "Frontiers in Medicine",
    "Frontiers in Oncology",
    "Frontiers in Psychology",
]

logging.basicConfig(
    level=logging.INFO, format="%(asctime)s  %(message)s", datefmt="%H:%M:%S"
)
log = logging.getLogger(__name__)


# ──────────────────────────────────────────────────────────────────────────────
# TAXONOMY LABELS
# ──────────────────────────────────────────────────────────────────────────────
def load_gpt_labels() -> dict:
    """Load GPT-generated labels mapping cluster_id -> short_label."""
    labels_file = GPT_LABELS_PATH / f"{CLUSTER_LEVEL}_labels.csv"
    if not labels_file.exists():
        log.warning("GPT labels not found at %s, using cluster IDs", labels_file)
        return {}
    
    df = pd.read_csv(labels_file)
    
    labels = {}
    for _, row in df.iterrows():
        cluster_id = int(row["cluster_id"])
        labels[cluster_id] = row["short_label"]
    
    log.info("       Loaded %d GPT labels from %s", len(labels), labels_file.name)
    return labels


# Global GPT labels (loaded once)
GPT_LABELS = {}

# BigQuery config for metadata
BQ_PROJECT = os.environ.get("BQ_PROJECT", "ocean-tech-adv-analytics-c-tfs")
BQ_DATASET = os.environ.get("BQ_DATASET", "scope_drift_raw")
RUN_TIMESTAMP = os.environ.get("RUN_TIMESTAMP", "")


def load_run_metadata() -> dict:
    """Load run metadata from BigQuery."""
    if not RUN_TIMESTAMP:
        log.warning("RUN_TIMESTAMP not set, skipping metadata load")
        return {}
    
    try:
        import pandas_gbq
        table = f"{BQ_PROJECT}.{BQ_DATASET}.run_metadata_{RUN_TIMESTAMP}"
        query = f"SELECT * FROM `{table}` LIMIT 1"
        df = pandas_gbq.read_gbq(query, project_id=BQ_PROJECT)
        
        if df.empty:
            log.warning("No metadata found in %s", table)
            return {}
        
        row = df.iloc[0].to_dict()
        # Parse journal_ids back from JSON string
        if "journal_ids" in row and isinstance(row["journal_ids"], str):
            row["journal_ids"] = json.loads(row["journal_ids"])
        
        log.info("       Loaded run metadata from BigQuery: %s", table)
        return row
    except Exception as e:
        log.warning("Could not load metadata from BigQuery: %s", e)
        return {}


# ──────────────────────────────────────────────────────────────────────────────
# LOAD DATA
# ──────────────────────────────────────────────────────────────────────────────
def load_cwts_data() -> pd.DataFrame:
    """Load and merge CWTS output files."""
    log.info("[1/5] Loading CWTS output files …")

    # Classification (int_id, micro, meso, macro)
    classif = pd.read_csv(
        CWTS_DIR / "classification.txt",
        sep="\t",
        header=None,
        names=["int_id", "micro", "meso", "macro"],
    )
    log.info(f"       classification.txt: {len(classif):,} rows")

    # Pub metadata (int_id, pub_id, is_frontiers, journal, date, title)
    meta = pd.read_csv(
        CWTS_DIR / "pub_metadata.txt",
        sep="\t",
        header=None,
        names=["int_id", "pub_id", "is_frontiers", "journal", "date", "title"],
        on_bad_lines="warn",
    )
    log.info(f"       pub_metadata.txt: {len(meta):,} rows")

    # Merge
    df = classif.merge(meta, on="int_id", how="inner")

    # Parse date
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df["pub_year"] = df["date"].dt.year
    df = df.dropna(subset=["pub_year"])
    df["pub_year"] = df["pub_year"].astype(int)

    # Filter to target journals
    if JOURNALS:
        df = df[df["journal"].isin(JOURNALS)].copy()

    log.info(f"       Merged & filtered: {len(df):,} papers")
    log.info(f"       Journals: {df['journal'].nunique()}")
    log.info(f"       {CLUSTER_LEVEL.title()} clusters: {df[CLUSTER_LEVEL].nunique()}")
    log.info(f"       Years: {df['pub_year'].min()}–{df['pub_year'].max()}")

    return df


def load_citations() -> pd.DataFrame:
    """Load citation links from local files."""
    log.info("[2/5] Loading citation links …")

    cit = pd.read_csv(
        CWTS_DIR / "cit_links.txt",
        sep="\t",
        header=None,
        names=["int_id1", "int_id2", "weight"],
    )
    log.info(f"       cit_links.txt: {len(cit):,} edges")

    return cit


# ──────────────────────────────────────────────────────────────────────────────
# LOAD DATA FROM BIGQUERY
# ──────────────────────────────────────────────────────────────────────────────
def load_cwts_data_from_bigquery() -> pd.DataFrame:
    """Load and merge CWTS data from BigQuery."""
    from google.cloud import bigquery
    
    log.info("[1/5] Loading data from BigQuery …")
    
    tbl_classif = f"{BQ_PROJECT}.{BQ_DATASET}.classification_raw_{RUN_TIMESTAMP}"
    tbl_pub_meta = f"{BQ_PROJECT}.{BQ_DATASET}.pub_metadata_raw_{RUN_TIMESTAMP}"
    
    log.info(f"       Classification: {tbl_classif}")
    log.info(f"       Pub metadata:   {tbl_pub_meta}")
    
    journals_str = ", ".join(f"'{j}'" for j in JOURNALS)
    
    client = bigquery.Client(project=BQ_PROJECT)
    
    query = f"""
    SELECT 
        c.int_id,
        c.micro,
        c.meso,
        c.macro,
        m.pub_id,
        m.is_frontiers,
        m.journal,
        m.date,
        m.title
    FROM `{tbl_classif}` c
    JOIN `{tbl_pub_meta}` m ON c.int_id = m.int_id
    WHERE m.journal IN ({journals_str})
    """
    
    df = client.query(query).to_dataframe()
    log.info(f"       Loaded {len(df):,} rows from BigQuery")
    
    # Parse date
    df["date"] = pd.to_datetime(df["date"], errors="coerce")
    df["pub_year"] = df["date"].dt.year
    df = df.dropna(subset=["pub_year"])
    df["pub_year"] = df["pub_year"].astype(int)
    
    log.info(f"       Journals: {df['journal'].nunique()}")
    log.info(f"       {CLUSTER_LEVEL.title()} clusters: {df[CLUSTER_LEVEL].nunique()}")
    log.info(f"       Years: {df['pub_year'].min()}–{df['pub_year'].max()}")
    
    return df


def load_citations_from_bigquery(valid_int_ids: set = None) -> pd.DataFrame:
    """Load citation links from BigQuery, filtered to relevant papers only."""
    from google.cloud import bigquery
    
    log.info("[2/5] Loading citation links from BigQuery …")
    
    tbl_cit_links = f"{BQ_PROJECT}.{BQ_DATASET}.cit_links_raw_{RUN_TIMESTAMP}"
    tbl_classif = f"{BQ_PROJECT}.{BQ_DATASET}.classification_raw_{RUN_TIMESTAMP}"
    tbl_pub_meta = f"{BQ_PROJECT}.{BQ_DATASET}.pub_metadata_raw_{RUN_TIMESTAMP}"
    
    client = bigquery.Client(project=BQ_PROJECT)
    
    # Filter citations to only those between papers in our journal set
    journals_str = ", ".join(f"'{j}'" for j in JOURNALS)
    
    query = f"""
    WITH journal_papers AS (
        SELECT c.int_id
        FROM `{tbl_classif}` c
        JOIN `{tbl_pub_meta}` m ON c.int_id = m.int_id
        WHERE m.journal IN ({journals_str})
    )
    SELECT cl.int_id1, cl.int_id2, cl.weight
    FROM `{tbl_cit_links}` cl
    WHERE cl.int_id1 IN (SELECT int_id FROM journal_papers)
      AND cl.int_id2 IN (SELECT int_id FROM journal_papers)
    """
    
    try:
        df = client.query(query).to_dataframe()
        log.info(f"       Loaded {len(df):,} citation edges (filtered to journal papers)")
    except Exception as e:
        log.warning(f"       Citation query failed: {e}")
        df = pd.DataFrame(columns=["int_id1", "int_id2", "weight"])
    
    return df


# ──────────────────────────────────────────────────────────────────────────────
# COMPUTE METRICS
# ──────────────────────────────────────────────────────────────────────────────
def compute_primary_clusters(df: pd.DataFrame, journal: str) -> set:
    """Find smallest set of clusters covering PRIMARY_COVERAGE of papers."""
    jdf = df[df["journal"] == journal]
    counts = jdf[CLUSTER_LEVEL].value_counts()
    total = counts.sum()

    primary = set()
    cumsum = 0
    for comm, count in counts.items():
        primary.add(comm)
        cumsum += count
        if cumsum >= total * PRIMARY_COVERAGE:
            break

    return primary


def compute_scatter_positions(df: pd.DataFrame, df_cit: pd.DataFrame) -> dict:
    """Compute x,y positions for papers using citation-based force-directed layout."""
    log.info("[3/5] Computing scatter positions …")
    
    import igraph as ig

    communities = df[CLUSTER_LEVEL].unique()
    n_comm = len(communities)
    cluster_to_idx = {c: i for i, c in enumerate(communities)}
    
    # Build paper-to-cluster mapping for citation aggregation
    paper_to_cluster = df.set_index("int_id")[CLUSTER_LEVEL].to_dict()
    valid_ids = set(paper_to_cluster.keys())
    
    # Filter citations to papers in our dataset
    df_cit_filtered = df_cit[
        df_cit["int_id1"].isin(valid_ids) & 
        df_cit["int_id2"].isin(valid_ids)
    ].copy()
    
    # Map to clusters and aggregate
    df_cit_filtered["src_cluster"] = df_cit_filtered["int_id1"].map(paper_to_cluster)
    df_cit_filtered["tgt_cluster"] = df_cit_filtered["int_id2"].map(paper_to_cluster)
    
    # Remove self-loops
    df_cit_filtered = df_cit_filtered[df_cit_filtered["src_cluster"] != df_cit_filtered["tgt_cluster"]]
    
    # Aggregate by cluster pair
    df_edges = (
        df_cit_filtered
        .groupby(["src_cluster", "tgt_cluster"])
        .agg(total_weight=("weight", "sum"))
        .reset_index()
    )
    
    log.info(f"       Cluster citation pairs: {len(df_edges):,}")
    
    # Build graph
    g = ig.Graph(n=n_comm)
    edges = []
    weights = []
    for _, row in df_edges.iterrows():
        src = cluster_to_idx.get(row["src_cluster"])
        tgt = cluster_to_idx.get(row["tgt_cluster"])
        if src is not None and tgt is not None and src != tgt:
            edges.append((src, tgt))
            weights.append(float(row["total_weight"]))
    
    # Compute layout
    if len(edges) > 10:
        g.add_edges(edges)
        g.es["weight"] = weights
        
        try:
            layout = g.layout_fruchterman_reingold(weights="weight", niter=500)
            coords = np.array(layout.coords)
        except Exception as e:
            log.warning(f"       Force layout failed: {e}, using circular")
            coords = _circular_layout(n_comm)
    else:
        log.info(f"       Not enough edges ({len(edges)}), using circular layout")
        coords = _circular_layout(n_comm)
    
    # Normalize to [0.1, 0.9]
    if len(coords) > 0:
        mins = coords.min(axis=0)
        maxs = coords.max(axis=0)
        ranges = maxs - mins
        ranges[ranges == 0] = 1  # avoid division by zero
        coords = (coords - mins) / ranges
        coords = coords * 0.8 + 0.1  # scale to [0.1, 0.9]
    
    comm_positions = {c: (float(coords[i, 0]), float(coords[i, 1])) for c, i in cluster_to_idx.items()}
    
    # Position papers with jitter around their community center
    positions = {}
    np.random.seed(42)
    for _, row in df.iterrows():
        cx, cy = comm_positions.get(row[CLUSTER_LEVEL], (0.5, 0.5))
        jitter = 0.06
        x = cx + np.random.uniform(-jitter, jitter)
        y = cy + np.random.uniform(-jitter, jitter)
        positions[row["int_id"]] = (float(x), float(y))

    log.info(f"       Positioned {len(positions):,} papers in {n_comm} clusters")
    return positions


def _circular_layout(n: int) -> np.ndarray:
    """Simple circular layout fallback."""
    angles = np.linspace(0, 2 * np.pi, n, endpoint=False)
    return np.column_stack([np.cos(angles), np.sin(angles)])


def compute_journal_stats(df: pd.DataFrame, positions: dict) -> list:
    """Compute statistics for each journal."""
    log.info("[4/5] Computing journal statistics …")

    journals_data = []
    years = sorted(df["pub_year"].unique())

    for journal in JOURNALS:
        jdf = df[df["journal"] == journal].copy()
        if jdf.empty:
            continue

        primary_clusters = compute_primary_clusters(df, journal)
        jdf["is_oos"] = ~jdf[CLUSTER_LEVEL].isin(primary_clusters)

        n_articles = len(jdf)
        n_oos = jdf["is_oos"].sum()
        oos_pct = (n_oos / n_articles * 100) if n_articles else 0

        # OOS by year
        oos_by_year = []
        for year in years:
            ydf = jdf[jdf["pub_year"] == year]
            if len(ydf) >= 10:
                y_oos = ydf["is_oos"].sum()
                oos_by_year.append(
                    {
                        "year": int(year),
                        "articles": int(len(ydf)),
                        "out_of_scope": int(y_oos),
                        "out_of_scope_pct": (
                            round(y_oos / len(ydf) * 100, 1) if len(ydf) else 0
                        ),
                    }
                )

        # Top communities for this journal
        comm_counts = jdf[CLUSTER_LEVEL].value_counts()
        top_comms = []
        for comm, count in comm_counts.head(10).items():
            label = GPT_LABELS.get(int(comm), f"Cluster {comm}")
            top_comms.append(
                {
                    "comm_id": int(comm),
                    "label": label,
                    "is_primary": comm in primary_clusters,
                    "papers_in_comm": int(count),
                    "share_of_journal": round(count / n_articles * 100, 1),
                }
            )

        # Scatter data (paper positions)
        scatter = []
        for _, row in jdf.iterrows():
            if row["int_id"] in positions:
                x, y = positions[row["int_id"]]
                scatter.append(
                    {
                        "x": round(x, 4),
                        "y": round(y, 4),
                        "c": int(row[CLUSTER_LEVEL]),
                        "t": str(row["title"] or "")[:50],
                    }
                )

        journals_data.append(
            {
                "name": journal,
                "articles": n_articles,
                "out_of_scope": int(n_oos),
                "out_of_scope_pct": round(oos_pct, 1),
                "n_primary_clusters": len(primary_clusters),
                "primary_coverage_pct": round(PRIMARY_COVERAGE * 100, 1),
                "top_communities": top_comms,
                "oos_by_year": oos_by_year,
                "scatter": scatter,
            }
        )

        log.info(
            f"       {journal}: {n_articles:,} papers, {oos_pct:.1f}% OOS, {len(primary_clusters)} primary clusters"
        )

    return journals_data


def compute_community_stats(df: pd.DataFrame) -> list:
    """Compute statistics for each community."""
    communities = []

    comm_counts = (
        df.groupby(CLUSTER_LEVEL)
        .agg(
            size=("int_id", "count"),
        )
        .reset_index()
    )

    for _, row in comm_counts.nlargest(100, "size").iterrows():
        comm_id = row[CLUSTER_LEVEL]
        cdf = df[df[CLUSTER_LEVEL] == comm_id]

        # Journal breakdown
        journal_counts = cdf["journal"].value_counts()

        dominant_journal = journal_counts.index[0] if len(journal_counts) else "Unknown"
        dominant_pct = (
            round(journal_counts.iloc[0] / len(cdf) * 100, 1)
            if len(journal_counts)
            else 0
        )

        top_journals = [
            {"name": j, "count": int(c), "pct": round(c / len(cdf) * 100, 1)}
            for j, c in journal_counts.head(3).items()
        ]

        # Use GPT label if available, otherwise fall back to cluster ID
        label = GPT_LABELS.get(int(comm_id), f"Cluster {comm_id}")
        
        communities.append(
            {
                "id": int(comm_id),
                "label": label,
                "size": int(row["size"]),
                "frontiers_pct": 100.0,
                "dominant_journal": dominant_journal,
                "dominant_pct": dominant_pct,
                "top_journals": top_journals,
            }
        )

    return communities


# ──────────────────────────────────────────────────────────────────────────────
# HTML GENERATION
# ──────────────────────────────────────────────────────────────────────────────
HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Journal Scope Dashboard</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
:root {
  --bg: #f6f8fa;
  --card: #ffffff;
  --text: #1a1f36;
  --muted: #5f6b7c;
  --border: #e3e7ee;
  --green: #1f8a4c;
  --red: #c93030;
  --amber: #d4a300;
  --blue: #2c5fa3;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.5;
}
header {
  background: var(--card);
  padding: 20px 24px;
  border-bottom: 1px solid var(--border);
}
header h1 { font-size: 1.4rem; font-weight: 700; margin-bottom: 4px; }
header p { color: var(--muted); font-size: 0.85rem; }
#scopeDesc { font-weight: 500; }

.kpi-row {
  display: flex;
  gap: 12px;
  padding: 16px 24px;
  background: var(--card);
  border-bottom: 1px solid var(--border);
  flex-wrap: wrap;
}
.kpi {
  flex: 1;
  min-width: 140px;
  padding: 12px 16px;
  background: var(--bg);
  border-radius: 8px;
}
.kpi-label { font-size: 0.75rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.5px; }
.kpi-value { font-size: 1.5rem; font-weight: 700; margin: 4px 0; }
.kpi-sub { font-size: 0.8rem; color: var(--muted); }

.tab-nav {
  display: flex;
  gap: 4px;
  padding: 12px 24px 0;
  background: var(--card);
}
.tab-btn {
  padding: 10px 20px;
  border: none;
  background: transparent;
  color: var(--muted);
  cursor: pointer;
  font-size: 0.9rem;
  border-bottom: 2px solid transparent;
  transition: all 0.2s;
}
.tab-btn:hover { color: var(--text); }
.tab-btn.active { color: var(--blue); border-bottom-color: var(--blue); font-weight: 600; }

.tab-content { display: none; padding: 20px 24px; }
.tab-content.active { display: block; }

.grid { display: grid; gap: 16px; grid-template-columns: repeat(auto-fit, minmax(500px, 1fr)); }
.card {
  background: var(--card);
  border-radius: 10px;
  padding: 16px;
  border: 1px solid var(--border);
}
.card h2 { font-size: 0.95rem; font-weight: 600; margin-bottom: 12px; }
.plot { height: 350px; }
.plot.tall { height: 420px; }
.plot.scatter { height: 450px; }

table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--border); }
th { color: var(--muted); font-weight: 600; font-size: 0.75rem; text-transform: uppercase; }
.num { text-align: right; font-variant-numeric: tabular-nums; }
.hi { color: var(--red); font-weight: 600; }
.lo { color: var(--green); }
.muted { color: var(--muted); font-size: 0.8rem; }

#scatterGrid { margin-top: 16px; }

footer {
  padding: 16px 24px;
  text-align: center;
  font-size: 0.8rem;
  color: var(--muted);
  border-top: 1px solid var(--border);
  background: var(--card);
}
</style>
</head>
<body>

<header>
  <h1>Journal Scope Dashboard</h1>
  <p>Generated <span id="snapStamp"></span> · <span id="scopeDesc"></span></p>
</header>

<div class="kpi-row" id="kpiRow"></div>

<nav class="tab-nav">
  <button class="tab-btn active" data-tab="overview">Overview</button>
  <button class="tab-btn" data-tab="scatter">Network Maps</button>
</nav>

<div id="tab-overview" class="tab-content active">
  <div class="grid">
    <div class="card" style="grid-column: 1 / -1;">
      <h2>Out-of-scope % by Year</h2>
      <div id="barOOSYear" class="plot tall"></div>
    </div>
  </div>
  <div class="card" style="margin-top: 16px;">
    <h2>Journal Summary</h2>
    <table id="tblJournal">
      <thead><tr>
        <th>Journal</th><th class="num">Articles</th><th class="num">Primary Clusters</th>
        <th class="num">Out of Scope</th><th class="num">OOS %</th><th>Top Community</th>
      </tr></thead>
      <tbody></tbody>
    </table>
  </div>
  <div class="card" style="margin-top: 16px;">
    <h2>Community Composition</h2>
    <table id="tblComm">
      <thead><tr>
        <th>Theme</th><th class="num">Size</th><th class="num">Frontiers %</th>
        <th>Dominant Journal</th><th>Top Journals</th>
      </tr></thead>
      <tbody></tbody>
    </table>
  </div>
</div>

<div id="tab-scatter" class="tab-content">
  <p style="margin-bottom: 16px; color: var(--muted);">
    Each bubble = community centroid. <span style="color: var(--green);">Green = in-scope (primary clusters)</span>, 
    <span style="color: var(--red);">Red = out-of-scope</span>. Size = paper count.
  </p>
  <div id="scatterGrid" class="grid"></div>
</div>

<footer>
  <div style="margin-bottom: 8px;">
    <span id="ftYears"></span> · <span id="ftCov"></span>% primary coverage · 
    <span id="ftJournals"></span> journals · <span id="ftPapers"></span> papers · 
    <span id="ftComms"></span> communities
  </div>
  <div id="ftSource" style="color: #8899a6; font-size: 0.75rem;"></div>
</footer>

<script>
const DATA = __DATA_JSON__;
__RENDER_SCRIPT__
</script>
</body>
</html>
"""


def build_html(data: dict):
    """Write the HTML dashboard."""
    log.info("[5/5] Writing HTML dashboard …")

    # Read render_script.js
    if RENDER_SCRIPT_PATH.exists():
        render_script = RENDER_SCRIPT_PATH.read_text(encoding="utf-8")
    else:
        log.error(f"       render_script.js not found at {RENDER_SCRIPT_PATH}")
        return

    # Build HTML
    data_json = json.dumps(data, separators=(",", ":"))
    html = HTML_TEMPLATE.replace("__DATA_JSON__", data_json)
    html = html.replace("__RENDER_SCRIPT__", render_script)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(html, encoding="utf-8")

    log.info(f"       Written to {OUTPUT_PATH}")
    log.info(f"       File size: {OUTPUT_PATH.stat().st_size / 1024:.1f} KB")


# ──────────────────────────────────────────────────────────────────────────────
# MAIN
# ──────────────────────────────────────────────────────────────────────────────
def main():
    global GPT_LABELS
    
    log.info("=" * 60)
    log.info("Building Scope Dashboard")
    log.info(f"Data source: {DATA_SOURCE.upper()}")
    log.info(f"Cluster level: {CLUSTER_LEVEL}")
    if DATA_SOURCE == "bigquery":
        log.info(f"Run timestamp: {RUN_TIMESTAMP}")
    log.info("=" * 60)

    # Load GPT labels
    GPT_LABELS = load_gpt_labels()
    
    # Load run metadata (from cwts_export.py)
    run_metadata = load_run_metadata()
    
    # Load data based on DATA_SOURCE toggle
    if DATA_SOURCE == "bigquery":
        df = load_cwts_data_from_bigquery()
        df_cit = load_citations_from_bigquery()
    else:
        df = load_cwts_data()
        df_cit = load_citations()

    # Compute positions and stats
    positions = compute_scatter_positions(df, df_cit)
    journals = compute_journal_stats(df, positions)
    communities = compute_community_stats(df)

    # Build data structure
    years = sorted(df["pub_year"].unique())
    data = {
        "meta": {
            "year_range": [int(years[0]), int(years[-1])] if years else [],
            "primary_cluster_coverage": PRIMARY_COVERAGE,
            "primary_cluster_level": CLUSTER_LEVEL,
            "oos_per_year_years": [int(y) for y in years],
        },
        "run_metadata": run_metadata,
        "journals": journals,
        "communities": communities,
    }

    # Write HTML
    build_html(data)

    log.info("=" * 60)
    log.info("Done!")
    log.info("=" * 60)


if __name__ == "__main__":
    main()
